//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorUrlishMarroquin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autore
    {
        public int AuthorID { get; set; }
        public string AuthorName { get; set; }
        public string AuthorCity { get; set; }
        public string Genre { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public Nullable<decimal> PiecesSold { get; set; }
    }
}
